ALTER TABLE "user"
  ADD COLUMN IF NOT EXISTS banned BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "banReason" TEXT,
  ADD COLUMN IF NOT EXISTS "banExpires" TIMESTAMPTZ;

ALTER TABLE "session"
  ADD COLUMN IF NOT EXISTS "impersonatedBy" TEXT;
