INSERT INTO plans (slug, name_fr, name_en, price_monthly, price_annual, tier, device_range_fr, device_range_en, features_fr, features_en, not_covered_fr, not_covered_en, service_time, is_popular, sort_order)
VALUES
  (
    'essentiel',
    'Essentiel',
    'Essential',
    1500,
    15000,
    'entry',
    'Smartphones jusqu''à 100 000 XOF',
    'Smartphones up to 100,000 XOF',
    '["Casse écran (avant)", "Assistance déclaration", "Suivi en ligne"]'::jsonb,
    '["Front screen damage", "Claim assistance", "Online tracking"]'::jsonb,
    '["Vol", "Oxydation", "Dommages esthétiques"]'::jsonb,
    '["Theft", "Water damage", "Cosmetic damage"]'::jsonb,
    '72h',
    false,
    1
  ),
  (
    'ecran-plus',
    'Écran+',
    'Screen+',
    3500,
    35000,
    'mid',
    'Smartphones jusqu''à 250 000 XOF',
    'Smartphones up to 250,000 XOF',
    '["Casse écran (avant + arrière)", "Assistance déclaration", "Suivi en ligne", "Prise en charge rapide"]'::jsonb,
    '["Screen damage (front + back)", "Claim assistance", "Online tracking", "Fast processing"]'::jsonb,
    '["Vol", "Oxydation", "Dommages esthétiques"]'::jsonb,
    '["Theft", "Water damage", "Cosmetic damage"]'::jsonb,
    '48h',
    true,
    2
  ),
  (
    'plus',
    'Plus',
    'Plus',
    6000,
    60000,
    'mid-high',
    'Smartphones jusqu''à 400 000 XOF',
    'Smartphones up to 400,000 XOF',
    '["Casse écran", "Panne & défaillance", "Oxydation", "Suivi en temps réel", "Réparation sous 48h"]'::jsonb,
    '["Screen damage", "Breakdown & malfunction", "Water damage", "Real-time tracking", "Repair within 48h"]'::jsonb,
    '["Vol", "Dommages esthétiques"]'::jsonb,
    '["Theft", "Cosmetic damage"]'::jsonb,
    '48h',
    false,
    3
  ),
  (
    'haute',
    'Haute',
    'Premium',
    10000,
    100000,
    'premium',
    'Smartphones jusqu''à 700 000 XOF',
    'Smartphones up to 700,000 XOF',
    '["Casse écran", "Panne & défaillance", "Oxydation", "Vol & perte", "Suivi en temps réel", "Réparation sous 24h", "Appareil de prêt"]'::jsonb,
    '["Screen damage", "Breakdown & malfunction", "Water damage", "Theft & loss", "Real-time tracking", "Repair within 24h", "Loaner device"]'::jsonb,
    '["Dommages esthétiques"]'::jsonb,
    '["Cosmetic damage"]'::jsonb,
    '24h',
    false,
    4
  ),
  (
    'totale',
    'Totale',
    'Total',
    15000,
    150000,
    'household',
    'Tous smartphones',
    'All smartphones',
    '["Casse écran", "Panne & défaillance", "Oxydation", "Vol & perte", "Multi-appareils (jusqu''à 3)", "Suivi en temps réel", "Réparation sous 12h", "Appareil de prêt", "Support prioritaire"]'::jsonb,
    '["Screen damage", "Breakdown & malfunction", "Water damage", "Theft & loss", "Multi-device (up to 3)", "Real-time tracking", "Repair within 12h", "Loaner device", "Priority support"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '12h',
    false,
    5
  );
